### ISSUE TITLE
fails with port already in use?

### ISSUE THREAD

**Issue by NetwarSystem** [asweigart/ezsheets#5] opened 2019-03-22 10:56 UTC
This is what I experience from the console when trying to using ezsheets. The credentials.json file is in the directory where I did this. 

Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ezsheets
>>> s = ezsheets.Spreadsheet('<URL OF ONE OF MY SHEETS>')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ezsheets/__init__.py", line 177, in __init__
    if not IS_INITIALIZED: init() # Initialize this module if not done so already.
  File "/usr/local/lib/python3.6/dist-packages/ezsheets/__init__.py", line 1522, in init
    creds = flow.run_local_server()
  File "/usr/local/lib/python3.6/dist-packages/google_auth_oauthlib/flow.py", line 407, in run_local_server
    host, port, wsgi_app, handler_class=_WSGIRequestHandler)
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 153, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

There is a lot going on with this box, not sure which port it's trying to use. My prior experience with Python internal server is command line, seeing it flagged to use 8000 or 8080, neither of which are in use here.

I'm baffled ... what do I do here?

sshd       4405            root    3u  IPv4    43703      0t0  TCP *:ssh (LISTEN)
sshd       4405            root    4u  IPv6    43705      0t0  TCP *:ssh (LISTEN)
anydesk    4417            root   27u  IPv4    51207      0t0  TCP *:7070 (LISTEN)
nxserver.  4436              nx    8u  IPv4    51329      0t0  TCP localhost:23783 (LISTEN)
redis-ser  4670           redis    6u  IPv4    46362      0t0  TCP localhost:6379 (LISTEN)
redis-ser  4670           redis    7u  IPv6    46363      0t0  TCP ip6-localhost:6379 (LISTEN)
netdata    5009         netdata    3u  IPv4    32280      0t0  TCP *:19999 (LISTEN)
netdata    5009         netdata    4u  IPv6    32281      0t0  TCP *:19999 (LISTEN)
netdata    5009         netdata   10u  IPv4    27151      0t0  TCP localhost:8125 (LISTEN)
nxd        5188              nx    3u  IPv4    32283      0t0  TCP *:4000 (LISTEN)
nxd        5188              nx    4u  IPv6    48338      0t0  TCP *:4000 (LISTEN)
java       5515   elasticsearch  642u  IPv6     2929      0t0  TCP localhost:9300 (LISTEN)
java       5515   elasticsearch  643u  IPv6     2938      0t0  TCP hp621:9300 (LISTEN)
java       5515   elasticsearch  927u  IPv6    21144      0t0  TCP localhost:9200 (LISTEN)
java       5515   elasticsearch  928u  IPv6    21145      0t0  TCP hp621:9200 (LISTEN)
java       6569            root   36u  IPv6    55534      0t0  TCP localhost:39581 (LISTEN)
java       6634            root   58u  IPv4    24017      0t0  TCP localhost:34851 (LISTEN)
java       6634            root 2658u  IPv4    23526      0t0  TCP *:http-alt (LISTEN)
keybase    9730          mewmew   18u  IPv4    56799      0t0  TCP localhost:16423 (LISTEN)
kbfsfuse   9872          mewmew    9u  IPv4      932      0t0  TCP localhost:16723 (LISTEN)
java      14455           neo4j  890u  IPv6 13144370      0t0  TCP *:7687 (LISTEN)
java      14455           neo4j  893u  IPv6 10564206      0t0  TCP *:7474 (LISTEN)
java      14455           neo4j  907u  IPv6 10564213      0t0  TCP *:7473 (LISTEN)
nxnode.bi 18764          mewmew   15u  IPv4  9761442      0t0  TCP localhost:12001 (LISTEN)
nxnode.bi 18764          mewmew   16u  IPv6  9778296      0t0  TCP ip6-localhost:afs3-callback (LISTEN)
nxnode.bi 18764          mewmew   17u  IPv4  9778297      0t0  TCP localhost:afs3-callback (LISTEN)
nxclient. 18786          mewmew   12u  IPv4  9766432      0t0  TCP localhost:25001 (LISTEN)
cupsd     20737            root    6u  IPv6 14577851      0t0  TCP ip6-localhost:ipp (LISTEN)
cupsd     20737            root    7u  IPv4 14577852      0t0  TCP localhost:ipp (LISTEN)
vmware-ho 21535            root   15u  IPv4 14574024      0t0  TCP *:https (LISTEN)
vmware-ho 21535            root   17u  IPv6 14574025      0t0  TCP *:https (LISTEN)
vmware-ho 21535            root   20u  IPv4 14574027      0t0  TCP localhost:8307 (LISTEN)
beam.smp  22293        rabbitmq   65u  IPv4 14167956      0t0  TCP *:25672 (LISTEN)
beam.smp  22293        rabbitmq   75u  IPv6 14167968      0t0  TCP *:amqp (LISTEN)
epmd      22405        rabbitmq    3u  IPv4 14184582      0t0  TCP *:epmd (LISTEN)
epmd      22405        rabbitmq    4u  IPv6 14184583      0t0  TCP *:epmd (LISTEN)
vmware-au 22595            root   10u  IPv6 14590037      0t0  TCP *:902 (LISTEN)
vmware-au 22595            root   11u  IPv4 14590038      0t0  TCP *:902 (LISTEN)
Discord   26847          mewmew   81u  IPv4  3737296      0t0  TCP localhost:6463 (LISTEN)
dropbox   29314          mewmew   88u  IPv6  9662411      0t0  TCP *:db-lsp (LISTEN)
dropbox   29314          mewmew  112u  IPv4  9717863      0t0  TCP localhost:17600 (LISTEN)
dropbox   29314          mewmew  118u  IPv4  9700219      0t0  TCP localhost:17603 (LISTEN)
dropbox   29314          mewmew  132u  IPv4  9662412      0t0  TCP *:db-lsp (LISTEN)
systemd-r 29818 systemd-resolve   13u  IPv4   165963      0t0  TCP localhost:domain (LISTEN)
teamviewe 32160            root   12u  IPv4 13894699      0t0  TCP localhost:5939 (LISTEN)

**Comment by NetwarSystem** [comment] 2019-03-22 11:04
Read the library, it's trying to open :8000 and no  barrier to that on my system. Here's the code snippet.

> if __name__ == '__main__':
>     with make_server('', 8000, demo_app) as httpd:
>         sa = httpd.socket.getsockname()
>         print("Serving HTTP on", sa[0], "port", sa[1], "...")
>         import webbrowser
>         webbrowser.open('http://localhost:8000/xyz?abc')
>         httpd.handle_request()  # serve one request, then exit
>

**Comment by asweigart** [comment] 2020-08-04 06:03
I tried to reproduce this by having a web server open on port 8080, which is the same port the google api module uses to create the token file. That's the only case where I can see this issue being caused, but I'm unable to reproduce this.

I'm going to close this issue unless I can figure out a way to reproduce. I'll keep an eye out for it though. Thanks!

**Closed as completed by asweigart** 2020-08-04 06:03 UTC
